# Generated by Django 5.2.4 on 2025-10-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0002_remove_choice_is_correct_usersurvey_useranswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersurvey',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='user',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильний варіант'),
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.DeleteModel(
            name='UserSurvey',
        ),
    ]
