# Generated by Django 5.2.4 on 2025-11-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0004_remove_choice_is_correct_usersurvey_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='page',
            field=models.PositiveIntegerField(default=1, verbose_name='Сторінка'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата проходження'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user_survey', 'question')},
        ),
    ]
