# Generated by Django 5.2.4 on 2025-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysystem', '0005_question_page_alter_usersurvey_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='page',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Варіант відповіді'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активне'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(default='Без назви', max_length=255, verbose_name='Назва'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
