# Generated by Django 5.2.5 on 2025-10-27 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва теґу')),
            ],
            options={
                'verbose_name': 'Теґ до події',
                'verbose_name_plural': 'Теґи до подій',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Початок події')),
                ('time_finish', models.TimeField(blank=True, null=True, verbose_name='Кінець події')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('topic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема')),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('cyan', 'Cyan'), ('purple', 'Purple'), ('pink', 'Pink')], default='blue', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='calendar_app.tag', verbose_name='Теґи')),
            ],
            options={
                'verbose_name': 'Подія в календарі',
                'verbose_name_plural': 'Події в календарі',
            },
        ),
    ]
