# Generated by Django 5.2.5 on 2025-09-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('magenta', 'Magenta'), ('cyan', 'cyan'), ('purple', 'purple'), ('dark-blue', 'Dark Blue')], default='blue', verbose_name='Колір')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Початок події')),
                ('time_finish', models.TimeField(blank=True, null=True, verbose_name='Кінець події')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
        ),
    ]
