# Generated by Django 5.2.4 on 2025-10-09 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва теґу')),
            ],
            options={
                'verbose_name': 'Теґ до події',
                'verbose_name_plural': 'Теґи до подій',
            },
        ),
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'verbose_name': 'Подія в календарі', 'verbose_name_plural': 'Події в календарі'},
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='color',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='PersonalEventColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('cyan', 'Cyan'), ('purple', 'Purple'), ('pink', 'Pink')], default='blue', max_length=255, verbose_name='Персоналізований колір події')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendarevent', verbose_name='Подія для персоналізованого коліру')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач, який вибирає колір події')),
            ],
            options={
                'verbose_name': 'Персоналізований колір для події',
                'verbose_name_plural': 'Персоналізовані кольори для подій',
            },
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='tags',
            field=models.ManyToManyField(blank=True, to='calendar_app.tag', verbose_name='Теґи'),
        ),
    ]
