# Generated by Django 5.2.5 on 2025-11-06 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journalapp.journalhomework')),
            ],
        ),
        migrations.CreateModel(
            name='JournalStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Н', 'Не оцінено'), ('1', '1 бал'), ('2', '2 бали'), ('3', '3 бали'), ('4', '4 бали'), ('5', '5 балів'), ('6', '6 балів'), ('7', '7 балів'), ('8', '8 балів'), ('9', '9 балів'), ('10', '10 балів'), ('11', '11 балів'), ('12', '12 балів')], max_length=2)),
                ('homework_grade', models.CharField(choices=[('Н', 'Не оцінено'), ('1', '1 бал'), ('2', '2 бали'), ('3', '3 бали'), ('4', '4 бали'), ('5', '5 балів'), ('6', '6 балів'), ('7', '7 балів'), ('8', '8 балів'), ('9', '9 балів'), ('10', '10 балів'), ('11', '11 балів'), ('12', '12 балів')], max_length=2)),
                ('date', models.DateField()),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_grades', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_grades', to='journalapp.lesson')),
            ],
        ),
    ]
