# Generated by Django 5.2.6 on 2025-10-09 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0002_journalstudents_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalstudents',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_grades', to='journalapp.lesson'),
        ),
        migrations.AlterField(
            model_name='journalstudents',
            name='student_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_grades', to=settings.AUTH_USER_MODEL),
        ),
    ]
