# Generated by Django 5.2.5 on 2025-10-18 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(choices=[('❤️', 'heart'), ('👎', 'dislike'), ('👌', 'okay'), ('😍', 'love-hearts'), ('👍', 'like'), ('😂', 'joy'), ('😮', 'surprised'), ('😢', 'sad'), ('😡', 'angry'), ('🎉', 'tada'), ('🙏', 'pray'), ('🔥', 'fire'), ('💯', '100'), ('✨', 'sparkles'), ('👏', 'clap'), ('💪', 'flexed-biceps'), ('😎', 'sunglasses'), ('🤔', 'thinking'), ('😴', 'sleeping'), ('🤗', 'hug'), ('😇', 'innocent'), ('😜', 'winking-tongue'), ('🤩', 'star-struck'), ('😤', 'triumph'), ('😱', 'scream'), ('🤪', 'zany-face'), ('🥳', 'partying-face'), ('🤯', 'exploding-head'), ('🥰', 'smiling-face-with-hearts')], max_length=10, verbose_name='Емодзі'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
