# Generated by Django 5.2.5 on 2025-10-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_reaction_unique_user_reaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
